---
- name: Install Nginx
  apt:
    name: "{{ nginx_package }}"
    state: present
    update_cache: yes  # This ensures that the package list is updated before installing
  become: yes

- name: Start and enable Nginx service
  service:
    name: "{{ nginx_service }}"
    state: started
    enabled: yes
  become: yes
